/** Starter template definitions — add new templates here */

export interface StarterTemplate {
	id: string;
	name: string;
	description: string;
	href: string;           // where clicking navigates
	previewBg: string;      // static asset path for the preview background
	previewText: string;    // placeholder headline shown in the card
	previewSource: string;  // source label shown in the card
	badge: string;          // chip label (e.g. "News")
	badgeColor: string;     // tailwind text colour class for the badge
}

export const STARTER_TEMPLATES: StarterTemplate[] = [
	{
		id: 'empty',
		name: 'Empty canvas',
		description: 'Start from a blank slide — add media, text, and overlays yourself',
		href: '/dashboard/studio?blank=1',
		previewBg: '',
		previewText: '',
		previewSource: '',
		badge: 'Blank',
		badgeColor: 'text-neutral-400',
	},
	{
		id: 'news',
		name: 'News Studio',
		description: 'AI writes the copy, Fal generates the images',
		href: '/dashboard/studio?template=news',
		previewBg: '/placeholders/carousel/news-template-placeholder.png',
		previewText: 'YOUR HEADLINE WILL APPEAR HERE',
		previewSource: 'Markets',
		badge: 'News',
		badgeColor: 'text-amber-400',
	},
	{
		id: 'image-quote',
		name: 'Image Quote',
		description: 'Top image + bold all-caps quote block',
		href: '/dashboard/studio?template=image-quote',
		previewBg: '/templates/image-quote/demo-bg.png',
		previewText: '',
		previewSource: '',
		badge: 'Quote',
		badgeColor: 'text-white/70',
	},
	{
		id: 'tweet',
		name: 'Tweet Carousel',
		description: 'Turn viral tweet exchanges into shareable slides',
		href: '/dashboard/studio?template=tweet',
		previewBg: '',
		previewText: '',
		previewSource: '',
		badge: 'Tweet',
		badgeColor: 'text-sky-400',
	},
	{
		id: 'text',
		name: 'Text Carousel',
		description: 'Dark branded text carousels for any niche',
		href: '/dashboard/studio?template=text',
		previewBg: '/placeholders/carousel/text-template-placeholder.png',
		previewText: '',
		previewSource: '',
		badge: 'Text',
		badgeColor: 'text-white/60',
	},
	// {
	// 	id: 'article',
	// 	name: 'Article Carousel',
	// 	description: 'Text + image breakdown slides with accent highlights',
	// 	href: '/dashboard/studio?template=article',
	// 	previewBg: '',
	// 	previewText: '',
	// 	previewSource: '',
	// 	badge: 'Article',
	// 	badgeColor: 'text-emerald-400',
	// },
	// {
	// 	id: 'video-story',
	// 	name: 'Video story',
	// 	description: 'Bold headline + vertical video — Shorts, Reels, TikTok',
	// 	href: '/dashboard/studio?template=video',
	// 	previewBg: '',
	// 	previewText: '',
	// 	previewSource: '',
	// 	badge: 'Video',
	// 	badgeColor: 'text-fuchsia-400',
	// },
	{
		id: 'black-text',
		name: 'Black text',
		description: 'Full-bleed dark slide with a bright hook line and long body copy',
		href: '/dashboard/studio?template=black-text',
		previewBg: '/placeholders/carousel/black-bg-placeholder.jpg',
		previewText: '',
		previewSource: '',
		badge: 'Carousel',
		badgeColor: 'text-sky-300',
	},
	{
		id: 'video-hook',
		name: 'Hook video',
		description: 'Black letterbox with a large AI-written white hook above the clip',
		href: '/dashboard/studio?template=hook',
		previewBg: '/placeholders/carousel/hook-video-placeholder.png',
		previewText: '',
		previewSource: '',
		badge: 'Video',
		badgeColor: 'text-fuchsia-400',
	},
	{
		id: 'video-creator',
		name: 'Creator hook',
		description: 'Profile row + bold hook text above a letterboxed clip',
		href: '/dashboard/studio?template=creator',
		previewBg: '/placeholders/carousel/creator-hook-placeholder.png',
		previewText: '',
		previewSource: '',
		badge: 'Video',
		badgeColor: 'text-fuchsia-400',
	},
	{
		id: 'video-text',
		name: 'Text on video',
		description: 'Full-bleed clip with centered outlined white text',
		href: '/dashboard/studio?template=pov',
		previewBg: '/placeholders/carousel/text-on-video-placeholder.png',
		previewText: '',
		previewSource: '',
		badge: 'Video',
		badgeColor: 'text-fuchsia-400',
	},
	{
		id: 'video-source',
		name: 'Highlight',
		description: 'Left-aligned hook with one neon highlighted word above a full-width clip',
		href: '/dashboard/studio?template=highlight',
		previewBg: '/placeholders/carousel/source-hook-placeholder.png',
		previewText: '',
		previewSource: '',
		badge: 'Video',
		badgeColor: 'text-lime-400',
	},
	{
		id: 'video-feature',
		name: 'Feature card',
		description: 'Headline + body with teal highlights and a rounded media card',
		href: '/dashboard/studio?template=feature',
		previewBg: '/placeholders/carousel/feature-card-placeholder.png',
		previewText: '',
		previewSource: '',
		badge: 'Video',
		badgeColor: 'text-teal-400',
	},
	{
		id: 'video-post',
		name: 'Clip post',
		description: 'Profile + casual hook above a letterboxed landscape clip',
		href: '/dashboard/studio?template=clip',
		previewBg: '/placeholders/carousel/clip-post-placeholder.png',
		previewText: '',
		previewSource: '',
		badge: 'Video',
		badgeColor: 'text-fuchsia-400',
	},
	{
		id: 'photo-topic',
		name: 'Topic card',
		description: 'Cinematic image on top with a centered title and body on black',
		href: '/dashboard/studio?template=topic',
		previewBg: '/placeholders/carousel/photo-topic-placeholder.png',
		previewText: '',
		previewSource: '',
		badge: 'Photo',
		badgeColor: 'text-sky-300',
	},
	{
		id: 'photo-caption',
		name: 'Photo caption',
		description: 'Full-bleed photo with a dark top gradient and left-aligned story copy',
		href: '/dashboard/studio?template=caption',
		previewBg: '/placeholders/carousel/photo-caption-placeholder.png',
		previewText: '',
		previewSource: '',
		badge: 'Photo',
		badgeColor: 'text-orange-300',
	},
	{
		id: 'white-thread',
		name: 'White thread',
		description: 'Clean white post with profile header and spaced story paragraphs',
		href: '/dashboard/studio?template=thread',
		previewBg: '/placeholders/carousel/white-thread-placeholder.png',
		previewText: '',
		previewSource: '',
		badge: 'Post',
		badgeColor: 'text-neutral-500',
	},
	{
		id: 'white-media',
		name: 'White media',
		description: 'White post with profile header, short copy, and a rounded media card',
		href: '/dashboard/studio?template=white-media',
		previewBg: '/placeholders/carousel/white-media-placeholder.png',
		previewText: '',
		previewSource: '',
		badge: 'Post',
		badgeColor: 'text-neutral-500',
	},
];
