/**
 * Auto-generated by `scripts/generate-template-demos.mjs`.
 * Do not edit by hand — re-run the script to refresh media + copy.
 */

export const GENERATED_DEMO_POSTS = {
	"news": {
		headline: "TEN YEARS AGO A [[HUNDRED DOLLAR INVESTMENT]] WOULD BE WORTH TWO THOUSAND",
		body: "Index funds spread your money across hundreds of companies automatically, so you're never betting everything on one ticker.",
		source: "Markets",
		imageUrl: "/templates/demos/news.jpg",
	},
	"image-quote": {
		body: "THE COMPANIES WINNING THE NEXT DECADE AREN'T THE ONES WITH THE MOST DATA.\n\nTHEY'RE THE ONES THAT SHIP WHILE EVERYONE ELSE IS STILL IN A MEETING.",
		footerLeft: "$",
		footerRight: "OPERATOR\nNOTES",
		imageUrl: "/templates/demos/image-quote.jpg",
		topRatio: 0.63,
	},
	"tweet": {
		topName: "Priya · Ops",
		topHandle: "@priyaops",
		bottomName: "Jordan Lee",
		bottomHandle: "@jordanbuilds",
		topText: "Hot take: your \"AI strategy\" is just ChatGPT with a Notion page.",
		bottomText: "Correct. And that Notion page has 14 stakeholders and zero shipped features.",
		imageUrl: "/templates/demos/tweet.jpg",
	},
	"text": {
		name: "Signal Over Noise",
		handle: "@signalovernoise",
		body: "Most founders optimize for looking busy.\n\nThe dangerous ones optimize for one metric customers actually feel.",
	},
	"black-text": {
		name: "Lena Ortiz",
		handle: "@lenabuilds",
		headline: "Charge more. Talk less. Ship weekly.",
		body: "Underpricing is a confidence problem dressed up as a pricing strategy.\n\nRaise the price until the wrong customers leave.\n\nThen build for the ones who stayed.",
	},
	"video-feature": {
		headline: "Claude just became the [[co-founder]] most teams were afraid to hire",
		body: "Brief it once. It remembers the codebase, the brand voice, and the deadlines. [[Ship tonight]]. Argue about process tomorrow.",
		highlightColor: "#2EE6C5",
		videoUrl: "/videos/demos/workspace.mp4",
		posterUrl: "/templates/demos/video-feature-poster.jpg",
	},
	"video-source": {
		headline: "[[3 DAILY HABITS]] EXPLAIN WHY JAPAN MASTERED [[SUSTAINABLE INNER PEACE.]]",
		highlightColor: "#39FF14",
		videoUrl: "/videos/demos/highlight-hook.mp4",
		posterUrl: "/templates/demos/highlight-hook-poster.jpg",
	},
	"video-text": {
		headline: "POV: you finally deleted the roadmap and asked one customer what hurts",
		videoUrl: "/videos/demos/neon-city.mp4",
		posterUrl: "/templates/demos/video-text-poster.jpg",
	},
	"video-creator": {
		name: "Revenue Lab",
		handle: "@revenuelab",
		headline: "She turned a 12-person waitlist into [[$28k MRR]] without a single ad",
		videoUrl: "/videos/demos/creator-cafe.mp4",
		posterUrl: "/templates/demos/video-creator-poster.jpg",
	},
	"video-hook": {
		headline: "The investor asked one question that ended the whole pitch",
		videoUrl: "/videos/demos/interview.mp4",
		posterUrl: "/templates/demos/video-hook-poster.jpg",
	},
	"video-fit": {
		headline: "",
		videoUrl: "/videos/demos/street-portrait.mp4",
		posterUrl: "/templates/demos/video-fit-poster.jpg",
	},
	"video-split": {
		videoUrl: "/videos/demos/duo-talk.mp4",
		posterUrl: "/templates/demos/video-split-poster.jpg",
	},
	"video-blur": {
		headline: "This $29 tool replaced a $400/mo subscription stack",
		videoUrl: "/videos/demos/product-hands.mp4",
		posterUrl: "/templates/demos/video-blur-poster.jpg",
	},
	"video-story": {
		watermark: "OPERATOR LOG",
		headline: "She almost quit on a Tuesday.\n\nBy Friday the same manager who ignored her had to ask how she fixed the funnel.",
		videoUrl: "/videos/demos/mentor.mp4",
		posterUrl: "/templates/demos/video-story-poster.jpg",
	},
	"video-post": {
		name: "Late Night Ops",
		handle: "@latenightops",
		headline: "The intern's 'dumb' idea just beat the entire growth team's A/B test 💀",
		videoUrl: "/videos/demos/team-win.mp4",
		posterUrl: "/templates/demos/video-post-poster.jpg",
		avatarUrl: "/templates/demos/video-post-avatar.jpg",
	},
	"brand-stack": {
		watermark: "Clip Desk",
		headline: "This founder got escorted out of his own launch for arguing with the venue about accessibility 👀",
		brand: "clipdesk.co/stories",
		videoUrl: "/videos/demos/crowd-night.mp4",
		posterUrl: "/templates/demos/brand-stack-poster.jpg",
		bottomMediaUrl: "/templates/demos/brand-stack-bottom.jpg",
	},
	"photo-caption": {
		headline: "No CS degree. No co-founder. No seed round.",
		body: "Just a kitchen table, a sleeping toddler, and a product that hit $12k MRR before anyone knew her name.",
		imageUrl: "/templates/demos/photo-caption.jpg",
	},
	"white-thread": {
		name: "Ava & Marcus Chen",
		handle: "@avaandmarcus",
		avatarUrl: "/templates/demos/white-thread-avatar.jpg",
		body: "Eighteen months ago I couldn't climb our stairs.\n\nToday I ran them twice — because Marcus cancelled his life to rebuild mine.\n\nHe learned every medication.\n\nHe sat through every silent hour.\n\nHe never made me feel like a burden.\n\nIf you have someone like that: tell them tonight.",
	},
	"white-media": {
		name: "archive hours",
		handle: "@archivehours",
		avatarUrl: "/templates/demos/white-media-avatar.jpg",
		imageUrl: "/templates/demos/white-media-attachment.jpg",
		body: "This illustration is 400 years old.\n\nIt was sitting in a museum basement until a 19-year-old posted a crop of it.\n\nNow every brand is stealing the palette.",
	},
} as const;

export type GeneratedDemoId = keyof typeof GENERATED_DEMO_POSTS;
